# permissions for end users to view componentproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentprovider-viewer-role
rules:
- apiGroups:
  - design.design.component.io
  resources:
  - componentproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - componentproviders/status
  verbs:
  - get
