# permissions for end users to edit componentproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentprovider-editor-role
rules:
- apiGroups:
  - design.design.component.io
  resources:
  - componentproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - componentproviders/status
  verbs:
  - get
