# permissions for end users to edit componentdefines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentdefine-editor-role
rules:
- apiGroups:
  - design.design.component.io
  resources:
  - componentdefines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - componentdefines/status
  verbs:
  - get
