
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - design.design.component.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - design.design.component.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - design.design.component.io
  resources:
  - componentdefines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - componentdefines/finalizers
  verbs:
  - update
- apiGroups:
  - design.design.component.io
  resources:
  - componentdefines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - design.design.component.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - design.design.component.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
