# permissions for end users to edit traitdefines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traitdefine-editor-role
rules:
- apiGroups:
  - design.design.component.io
  resources:
  - traitdefines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - design.design.component.io
  resources:
  - traitdefines/status
  verbs:
  - get
